---
title: "Vdem Mapping"
format: html
editor: visual
---

## Vdem Mapping

```{r}
library(tidyverse)
library(rio)
library(plotly)
library(sf)
library(ggplot2)

#install.packages("choroplethr", dependencies = TRUE)
#install.packages("ggrepel")

#install.packages("choroplethrMaps")
library(choroplethrMaps)

vdem_data <- read_csv("VDEM.csv")
head(vdem_data)
data(vdem_data)

#install.packages("ggmap")
library(ggmap)
```

loading the world map into R

```{r}
#install.packages("rnaturalearth")
#install.packages("sf")
#install.packages("rnaturalearthdata")
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(ggplot2)

world <- ne_countries(scale = "medium", returnclass ="sf") %>%
   filter(continent != "Antarctica")

ggplot(world) +
  geom_sf(aes(geometry = geometry))+ 
  theme_void()
```

Canada and USA

```{r}
Canada <- ne_countries(country ="Canada")
ggplot(Canada) + 
  geom_sf()

us_states <- ne_states(country = "United States of America")
ggplot(us_states) +
  geom_sf() + 
  coord_sf(
    xlim = c(-125, -66), # longitude 
    ylim = c(24, 50), # latitude 
    expand = FALSE
  )

```

Filter for only NATO countries

```{r}

vdem_data <- vdem_data[, c("country_name", "v2x_polyarchy")]

vdem_data <- left_join(world, vdem_data, by = c("name" = "country_name"))

ggplot(vdem_data) +
  geom_sf(aes(fill = v2x_polyarchy), color = "white", linewidth = 0.2) +
  scale_fill_viridis_c(
    limits = c(0, 1),
    breaks = c(0, 0.25, 0.50, 0.75, 1),
    labels = c("0", "0.25", "0.50", "0.75", "1"),
    name = "Electoral Democracy (v2x_polyarchy)"
  ) +
  theme_void()

```

```{r}
library(plotly)

p <- ggplot(vdem_data) +
  geom_sf(aes(fill = v2x_polyarchy), color = "white", linewidth = 0.2) +
  scale_fill_viridis_c(
    limits = c(0, 1),
    breaks = c(0, 0.25, 0.50, 0.75, 1),
    labels = c("0", "0.25", "0.50", "0.75", "1"),
    name = "Electoral Democracy (v2x_polyarchy)"
  ) +
  theme_void()

ggplotly(p)
```
